### ISSUE TITLE
Datasets cannot be deleted

### ISSUE THREAD

**Issue by massimosgrelli** [secrez/secrez#119]
It would be useful to delete datasets once created. If a dataset is empty that should be without further confirmation. Otherwise, there should be an option to force deletion.

**Comment by sullof** [comment]
I think this can be implemented that:

1. All the files in the dataset are move to the `trash` dataset, like removing a folder.
2. The dataset is deleted.

This way, if the user makes mistakes, can still recover the deleted files from the `trash` dataset.

@massimosgrelli what do you think?

**Comment by massimosgrelli** [comment]
I think it's a good solution.
