### ISSUE TITLE
File attributes visibility

### ISSUE THREAD

**Issue by massimosgrelli** [secrez/secrez#120]
I don't find a way to display file attributes (e.i. ls -al doesn't seem to work as expected).

**Comment by sullof** [comment]
Permissions are `0x700`.
Are you talking about size and date of creation?

**Comment by sullof** [comment]
What about an output like this:

```
 128 Feb 11  2019 AWS/
 192 Nov  5  2018 Applications/
  96 Mar 20  2019 bar.conf
2464 Jan  1 15:52 Desktop/
 832 Dec  4 15:36 Documents/
2304 Jan  2 13:09 README
 352 Feb 24  2020 file.txt

```

**Comment by massimosgrelli** [comment]
Yes that would be useful or something more like a linux attribute list—except permissions.

**Comment by sullof** [comment]
Or
```
2   128 Feb 11  2019 AWS/
3   192 Nov  5  2018 Applications/
4    96 Mar 20  2019 bar.conf
1  2464 Jan  1 15:52 Desktop/
1    832 Dec  4 15:36 Documents/
4  2304 Jan  2 13:09 README
3   352 Feb 24  2020 file.txt

```
where the first number is the number of versions, that you can see running, for example
```
cat somefile -a
```
